package capstone.safeline.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "group_messages")
data class GroupMessageEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val messageUuid: String, // The UUID generated by the server
    val groupId: String,     // The room this message belongs to
    val senderId: String,    // Who sent it in the group
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val status: String = "PENDING" // Options: PENDING, SENT, DELIVERED
)